### ISSUE TITLE
开源？

### ISSUE THREAD

**Issue by lq08025107** [gxchain/gxb-release#1]
你们的开源的风格与众不同，找不到一行源代码

**Comment by lanhaoxiang** [comment]
@lq08025107 开源时间是近期噢
这个项目是未开源前用于存放项目release的，请关注官方发布的开源进程， 核心库开源关注 [gxchain/gxb-core](https://github.com/gxchain/gxb-core)

已开源部分:
 [gxchain/gxb-box 交易盒子](https://github.com/gxchain/gxb-box)
 [gxchain/gxb-light 轻钱包](https://github.com/gxchain/gxb-light)
 [gxchain/gxb-explorer 区块链浏览器](https://github.com/gxchain/gxb-explorer)

添加watch可以最快的方式知道进度
